#!/bin/bash

# Init file for crosscoap service. It must go in /etc/init.d/crosscoap

GOPATH=/opt/go
PATH=$PATH:$GOPATH/bin
CONFIG=/etc/crosscoap.conf

if [ -f $CONFIG ]; then
    . $CONFIG

    crosscoap -accesslog $ACCESSLOG -listen $LISTEN -errorlog $ERRORLOG -backend $BACKEND
else
    echo "No configuration file defined for crosscoap"
fi
